uabipfe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g uabipfe.c \
		-o uabipfe.out \
		-lgmp -lcifer 

msp:
	gcc	-L/usr/local/lib/libcifer.so \
		-g msp.c \
		-o msp.out \
		-lgmp -lcifer 		

uzpipfe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g uzpipfe.c \
		-o uzpipfe.out \
		-lgmp -lcifer 

fhipe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g fhipe.c \
		-o fhipe.out \
		-lgmp -lcifer 

uzpipfe_27:
	gcc	-L/usr/local/lib/libcifer.so \
		-g uzpipfe_27.c \
		-o uzpipfe_27.out \
		-lgmp -lcifer 