uabipfe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g uabipfe.c \
		-o uabipfe.out \
		-lgmp -lcifer 

uzpipfe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g uzpipfe.c \
		-o uzpipfe.out \
		-lgmp -lcifer 

fhipe:
	gcc	-L/usr/local/lib/libcifer.so \
		-g fhipe.c \
		-o fhipe.out \
		-lgmp -lcifer 
